project_id = "otodloskmmhpwxafcgcc"

[functions.create-checkout]
verify_jwt = true

[functions.analyze-security]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.toggle-admin-pro]
verify_jwt = true

[functions.get-invoices]
verify_jwt = true

[functions.validate-stripe-promo]
verify_jwt = false
